project:
  type: website
  output-dir: docs

website:
  favicon: media/claude-brands-solid-full.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - interests.qmd
      - resume.qmd
    right: 
      - icon: github
        href: https://github.com/sumaiyaalvi
        target: _blank

format:
  html:
    theme:
      light: Morph
      dark: Solar
    css: styles.css
    toc: true
    page-layout: full



