project:
  type: website
  output-dir: docs

website:
  title: "Sumaiya Alvi"
  site-url: https://sumaiyaalvi.github.io/
  favicon: media/claude-brands-solid-full.svg
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Sumaiya Alvi
      - about.qmd
      - interests.qmd
      - projects.qmd
      - resume.qmd
    right: 
      - icon: github
        href: https://github.com/sumaiyaalvi
        target: _blank

format:
  html:
    theme:
      - Morph
      - styles.scss
    mainfont: DM Sans
    toc: false
    page-layout: full



